#USE semester project 2;

-- Delete data
#ALTER TABLE staff DROP FOREIGN KEY fk_staff_store , DROP FOREIGN KEY fk_staff_address;
#DELETE FROM address ;
#DELETE FROM author ;
#DELETE FROM books ;
#DELETE FROM borrow ;
#DELETE FROM categories ;
#DELETE FROM reservations ;
#DELETE FROM review ;
#DELETE FROM school ;
#DELETE FROM school_admin ;
#ALTER TABLE store CHANGE COLUMN manager_staff_id manager_staff_id INT UNSIGNED NULL;
#update store set manager_staff_id=null;
#DELETE FROM users ;
#ALTER TABLE store CHANGE COLUMN manager_staff_id manager_staff_id INT UNSIGNED NOT NULL;




LOAD DATA INFILE "C:/Dummy Data/MOCK_DATA Authors.csv"
INTO TABLE author
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE "C:/Dummy Data/MOCK_DATA categories.csv"
INTO TABLE categories
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE "C:/Dummy Data/MOCK_DATA Address 2.csv"
INTO TABLE address
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
LOAD DATA INFILE "C:/Dummy Data/MOCK_DATA school admin.csv"
INTO TABLE school_admin
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE "C:/Dummy Data/MOCK_DATA School.csv"
INTO TABLE school
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE "C:/Dummy Data/MOCK_DATA Books 2.csv"
INTO TABLE books
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE "C:/Dummy Data/MOCK_DATA author_books.csv"
INTO TABLE author_book
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE "C:/Dummy Data/MOCK_DATA author_books.csv"
INTO TABLE category_book
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA INFILE "C:/Dummy Data/MOCK_DATA users.csv"
INTO TABLE users
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;